![Numpy Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

#Why Numpy?
https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference?source=post_page-----f1b582a413f1----------------------

# Installing Numpy

In [30]:
#!pip install numpy

In [2]:
import numpy as np

print (np.__version__)

1.17.1


# Numpy Arrays

Array Initialization

In [3]:
#List - [1, 6, 0, 9, 2]
arr = np.array([1, 6, 0, 9, 2])
print (arr)

[1 6 0 9 2]


Arithmetical Operations

In [4]:
#Addition
print (arr + 10)

#Multiplication
print (arr * 10)

#Subtraction
print (arr - 10)

#Division
print (arr / 10)

[11 16 10 19 12]
[10 60  0 90 20]
[ -9  -4 -10  -1  -8]
[0.1 0.6 0.  0.9 0.2]


Array Attributes

In [5]:
#Shape
print (arr.shape)

#Data Type
print (arr.dtype)

(5,)
int32


Multi-dimensional Arrays

In [6]:
#Two-Dimensional
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print (arr_2d)
print (arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [7]:
#Three-Dimensional
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print (arr_3d)
print (arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# Ones and Zeros

In [8]:
#Initializing Zeros
zer = np.zeros((3, 3))

print (zer)
print (zer.shape)
print (zer.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
float64


In [9]:
zer = np.zeros((3, 3), dtype=int)

print (zer.shape)
print (zer.dtype)

(3, 3)
int32


In [10]:
zer = np.ones((3, 3), dtype=int)

print (zer)
print (zer.shape)
print (zer.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
(3, 3)
int32


# Reshaping

In [11]:
#Before
arr = np.array([(1, 2, 3), (4, 5, 6)])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
#Reshape
arr_re = arr.reshape((3, 2))

print(arr_re)
print(arr_re.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [13]:
#Flatten
arr_flat_ = arr.flatten()

print (arr_flat_)

[1 2 3 4 5 6]


# Horizontal and Vertical Stacking

In [14]:
first = np.array([1,2,3])
second = np.array([4,5,6])

In [15]:
# Horitzontal Stack
print (np.hstack((first, second)))

[1 2 3 4 5 6]


In [16]:
# Vertical Stack
print (np.vstack((first, second)))

[[1 2 3]
 [4 5 6]]


# Generating Data

Arange

In [17]:
print (np.arange(1, 10))

print (np.arange(1, 10, 2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


Linspace

In [18]:
print (np.linspace(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]


Logspace

In [19]:
print (np.logspace(1, 10, 5))

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


Random Numbers

In [20]:
print (np.random.normal(5, 0.5, 10))

[5.4102979  4.70823452 5.23165199 4.66767351 3.3039154  4.695103
 4.16927226 5.08799002 3.97798117 5.6126267 ]


![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Empirical_Rule.PNG/350px-Empirical_Rule.PNG)

# Indexing

In [21]:
arr = np.array ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print (arr[0])

print (arr[2:5])

print (arr[:5])

print (arr[5:])

0
[2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [22]:
arr_2d = np.array([(0, 1, 2), 
                   (3, 4, 5)])

print (arr_2d)

print (arr_2d[1])

print (arr_2d[:2, 1])

[[0 1 2]
 [3 4 5]]
[3 4 5]
[1 4]


# Basic Statistical Functions

In [23]:
normal_array = np.random.normal(5, 0.5, 10)

print (normal_array)

[4.37381212 4.79704846 5.04713276 4.52575075 5.09281789 4.5362486
 4.55444304 5.48436725 4.48219718 5.45579857]


In [24]:
### Min 
print (np.min(normal_array))

### Max 
print (np.max(normal_array))

### Mean 
print (np.mean(normal_array))

### Median
print (np.median(normal_array))

### Standard Deviation
print (np.std(normal_array))

4.373812119564061
5.48436724993763
4.834961662490409
4.675745750562717
0.3899670705284782


# Product of Arrays

In [25]:
first = np.array([1, 2])
second = np.array([4, 5])

In [26]:
# Element-by-Element
print (first * second)

[ 4 10]


In [27]:
# Dot Product
print (np.dot(first, second))

14


In [28]:
first = [[1,2],[3,4]] 
second = [[5,6],[7,8]] 

# Matrix Multiplication
print (np.matmul(first, second))

[[19 22]
 [43 50]]


# Determinant

In [29]:
print (np.linalg.det(second))

-2.000000000000005


#Futher Numpy Documentation

https://numpy.org/