![Numpy Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

#Why Numpy?
https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference?source=post_page-----f1b582a413f1----------------------

# Installing Numpy

In [ ]:
#pip

In [ ]:
#importing numpy

1.17.5
3.1.2


# Numpy Arrays

Array Initialization

In [ ]:
#List - [1, 6, 0, 9, 2]

[1 6 0 9 2]


Arithmetical Operations

In [ ]:
#Addition


#Multiplication


#Subtraction


#Division


[11 16 10 19 12]
[10 60  0 90 20]
[ -9  -4 -10  -1  -8]
[0.1 0.6 0.  0.9 0.2]


Array Attributes

In [ ]:
#Shape


#Data Type


(5,)
int64


Multi-dimensional Arrays

In [ ]:
#Two-Dimensional


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#Three-Dimensional


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# Ones and Zeros

In [ ]:
#Initializing Zeros


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
float64


In [ ]:
#Initializing Zeros with Dtype

(3, 3)
int64


In [ ]:
#Initializing Ones with Dtype


[[1 1 1]
 [1 1 1]
 [1 1 1]]
(3, 3)
int64


# Reshaping

In [ ]:
#Simple 2D Array (before Reshape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#Reshape


[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#Flatten


[ 0  1  2  3  4  5  6  7  8  9 10]


# Horizontal and Vertical Stacking

In [ ]:
#Initialzing two simple 1D arrays


In [ ]:
# Horitzontal Stack


[1 2 3 4 5 6]


In [ ]:
# Vertical Stack


[[1 2 3]
 [4 5 6]]


# Generating Data

Arange

In [ ]:
#Range: 1 to 10


#Range: 1 to 10 with Spacing = 2


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


Linspace

In [ ]:
#Array with 5 elements in range = 1 to 10


[ 1.    3.25  5.5   7.75 10.  ]


Logspace

In [ ]:
#Array with 5 elements in range = 1 to 10 (logarithmically)


[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


Random Numbers

In [ ]:
#Random Numbers distributed Normally


[5.19783947 5.19810312 4.89174423 5.27046979 4.85923082 4.82354455
 4.9952682  5.24390606 5.72429108 4.2670679 ]


![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Empirical_Rule.PNG/350px-Empirical_Rule.PNG)

# Indexing

In [ ]:
#Simple 1D array


#Accessing Index


#Slicing 2 to 5


#Slicing 0 to 5


#Slicing 5 to End


0
[2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [ ]:
#Simple 2D array


#2D Array


#2D Array Row by Index


#2D Array Row Sliced and Column by Index


[[0 1 2]
 [3 4 5]]
[3 4 5]
[1 4]


# Basic Statistical Functions

In [ ]:
#Initialize Random Normally Distributed numbers
#mean = 5
#standard deviation = 0.5
#size = 10

[5.39522081 4.24378144 5.09331284 5.10723983 5.68104555 4.74492819
 5.06985298 4.29434351 5.2905326  5.06362356]


In [ ]:
### Min 


### Max 


### Mean 


### Median


### Standard Deviation


4.2437814448148385
5.681045545229229
4.998388131625137
5.081582909481604
0.4322522423040592


# Product of Arrays

In [ ]:
#Two simple 1D arrays
first = np.array([1, 2])
second = np.array([4, 5])

In [ ]:
# Element-by-Element


[ 4 10]


In [ ]:
# Dot Product


14


In [ ]:
#Two simple Matrices
first = [[1,2],[3,4]] 
second = [[5,6],[7,8]] 

# Matrix Multiplication


[[19 22]
 [43 50]]


# Determinant

In [ ]:
#linalg Determinant


-2.000000000000005


#Futher Numpy Documentation

https://numpy.org/